---
title: "Methodology"
author: "Alex Pavlakis"
output: 
  html_document:
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, cache = T)
```


Yapa is a simple poll aggregator that estimates state-level support for US presidential candidates by combining state-level polls with prior election results.  

# Model

The number of respondents in each poll ($y_p$) is drawn from the total respondents in than poll $n_p$ at proportion specific to the candidate and the state $\theta_{s, c}$.  That rate parameter is samples based on a candidate-state specific mean $\alpha_{c, s}$ and state specific variance $t_s$.  The sum of proportions for each candidate must equal one.

$$
\begin{align}
y_{p, c} &\sim Binomial(n_p, \theta_{s, c}) \\
\theta_{s, c} &\sim Normal(\alpha_{s, c}, \tau_{s}) \\
\sum_c \theta_s &= 1 
\end{align}
$$

In this model, we use the results of the previous presidential election in each state as prior $\alpha$.

## Assumptions

1. Polls are unbiased _on average_ (unrealistic).
2. There is no time-trend in the true underlying support for each candidate in each state, just different realizations from a distribution (unrealistic).
3. State general election results are unlikely to deviate more than 20 percentage points from their results in the previous general election.

